url: "https://karthik-vasisht.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Karthik Vasisht" # the name of your site, e.g. ACME Corp.
description: "Karthik's academic website  "
