menu:
  # - {name: 'people', url: '/people'}
  # - {name: 'publications', url: '/publications'}
  - {name: 'About', url: '/'}
  - {name: 'Research', url: '/research/'}
  - {name: 'Talks', url: '/talks/'}
  - {name: 'Outreach', url: '/outreach/'}

people:
  - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
  - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
  - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
  - {name: 'Vector Calculus', url: 'vector-calculus'}
  - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
  - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
  - {icon: 'github', link: 'https://github.com/karthik-vasisht'}
  # - {icon: 'twitter', link: 'https://twitter.com/paululele'}
  # - {icon: 'instagram', link: 'https://instagram.com/paululele'}
  - {icon: 'linkedin', link: 'https://linkedin.com/in/karthikvasisht'}

contacts:
  - {name: 'Karthik Vasisht', title: 'PhD Student', department: 'Mathematics', institution: 'Purdue University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
